stages:
  - build
  - deploy

build alko-students-front:
  stage: build
  image: node:latest
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - dist
  tags:
    - alkostudents-front-tag
  variables:
    api: localhost/api
  script:
    - npm ci
    - npm run build

deploy alko-students-front:
  stage: deploy
  tags:
    - alkostudents-front-tag
  script:
    - mkdir -p ~/front-deployment
    - rm -rf ~/front-deployment/*
    - cp -r dist/. ~/front-deployment
